# Generated by Django 3.2.12 on 2022-05-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='recommendations',
            field=models.ManyToManyField(related_name='_movies_movie_recommendations_+', to='movies.Movie'),
        ),
    ]
