# Generated by Django 3.2.12 on 2022-05-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_original_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='original_title',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='overview',
        ),
    ]
