# Generated by Django 3.2.12 on 2022-05-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20220524_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='movies/<django.db.models.fields.CharField>/')),
                ('image2', models.ImageField(upload_to='movies/<django.db.models.fields.CharField>/')),
                ('image3', models.ImageField(upload_to='movies/<django.db.models.fields.CharField>/')),
                ('image4', models.ImageField(upload_to='movies/<django.db.models.fields.CharField>/')),
                ('image5', models.ImageField(upload_to='movies/<django.db.models.fields.CharField>/')),
            ],
        ),
    ]
