# Generated by Django 3.2.12 on 2022-05-25 11:38

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_mapmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapmovie',
            name='image1',
            field=models.ImageField(upload_to=movies.models.map_movie_image_path),
        ),
        migrations.AlterField(
            model_name='mapmovie',
            name='image2',
            field=models.ImageField(upload_to=movies.models.map_movie_image_path),
        ),
        migrations.AlterField(
            model_name='mapmovie',
            name='image3',
            field=models.ImageField(upload_to=movies.models.map_movie_image_path),
        ),
        migrations.AlterField(
            model_name='mapmovie',
            name='image4',
            field=models.ImageField(upload_to=movies.models.map_movie_image_path),
        ),
        migrations.AlterField(
            model_name='mapmovie',
            name='image5',
            field=models.ImageField(upload_to=movies.models.map_movie_image_path),
        ),
    ]
