# Generated by Django 3.2.12 on 2022-05-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20220525_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_key',
            field=models.TextField(),
        ),
    ]
