# Generated by Django 3.2.12 on 2022-05-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='watch_day',
            field=models.DateField(),
        ),
    ]
