# Generated by Django 3.2.12 on 2022-05-22 10:58

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_followings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='profile_images/17ccba6c1b84f8bd6.jpeg', upload_to='profile_images/'),
        ),
    ]
